### PR TITLE
refactor: use new `exists` and `linked` subcommands

### PR DESCRIPTION
**Pull request by josegonzalez**
These simplify connecting datastores significantly.

The new subcommand pull requests are currently being tested on CI and should be available for use in all official datastores by EOD.

### CODE REVIEW

**Comment by josegonzalez** [comment]
Semi-related is this repo: https://github.com/josegonzalez/dokku-service-attacher

I'd like to rewrite the app.json plugin support to be in golang, and it'll probably subsume some of the functionality you have in this plugin. We'll see!

**Comment by crisward** [comment]
Sounds interesting. Will keep an eye out for it.

**Comment by josegonzalez** [comment]
The subcommands have been released.

**Comment by crisward** [comment]
Thanks... I've been reticent to merge this as I run several severs with dokku, and they're using various versions. I probably should tag releases.

**Comment by josegonzalez** [comment]
I should probably tag releases :D

**Comment by josegonzalez** [comment]
_bump_ We now tag releases for the datastore plugins.

**Comment by crisward** [comment]
Thanks - merged this into master and left old version on v1 tag.

**Pull request merged**
